steps:
  # 1. Construir la imagen Docker usando la caché para optimizar tiempos
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/cosmotech-web:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/cosmotech-web:latest'
      - '.'

  # 2. Subir la imagen a Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cosmotech-web', '--all-tags']

  # 3. Desplegar la imagen en Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cosmotech-web'
      - '--image'
      - 'gcr.io/$PROJECT_ID/cosmotech-web:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'

images:
  - 'gcr.io/$PROJECT_ID/cosmotech-web:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/cosmotech-web:latest'

options:
  logging: CLOUD_LOGGING_ONLY

