import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import Script from 'next/script';
const font = DM_Sans({
  weight: ['100', '200', '300', '500', '700'],
  subsets: ['latin'],
  style: ['normal', 'italic'],
})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <Script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></Script>
       <body className={font.className}>
        {children}
      </body>
    </html>
  );
}
